name: UIMA Regression Tests
description: Run UIMA regression test suite using cucumber and gherkin scenarios.
inputs:
  input1:
    description: 'Input 1 description'
    required: true
  input2:
    description: 'Input 2 description'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Checkout Action Repository
      shell: bash
      run: |
        REPO_URL="https://github.com/UIMA-Messaging/uima-test-suite.git"
        git clone $REPO_URL
        cd $REPO_NAME

    - name: Echo Input 1
      shell: bash
      run: |
        echo ${{ inputs.input1 }}

    - name: Echo Input 2
      shell: bash
      run: |
        echo ${{ inputs.input2 }}

    - name: Cucumber Tests
      shell: bash
      run: |
        mvn -version
        mvn clean test
