name: UIMA Regression Tests
description: Run UIMA regression test suite using cucumber and gherkin scenarios.
inputs:
  repo:
    description: 'Repository URL where Cucumber Java tests reside in'
    required: true
  branch:
    description: 'Optional branch to target tests on a specific branch'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Clone Cucumber Repository
      shell: bash
      run: |
        echo ${{ inputs.repo }}
        echo ${{ inputs.branch }}

        REPO_URL="https://github.com/UIMA-Messaging/uima-test-suite.git"
        git clone $REPO_URL

    - name: Run Cucumber Tests
      shell: bash
      run: |
        cd uima-test-suite
        mvn clean test
