name: UIMA Regression Tests
description: Run UIMA regression test suite using cucumber and gherkin scenarios.
inputs:
  input1:
    description: 'Input 1 description'
    required: true
  input2:
    description: 'Input 2 description'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Checkout Action Repository
      shell: bash
      run: |
        REPO="UIMA-Messaging/uima-test-suite"
        REPO_OWNER=$(echo $REPO | cut -d'/' -f1)
        REPO_NAME=$(echo $REPO | cut -d'/' -f2)
        API_URL="https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$GITHUB_WORKFLOW/runs/$GITHUB_RUN_ID"
        AUTH_HEADER="Authorization: Bearer $GITHUB_TOKEN"
        RESPONSE=$(curl -sSL -H "$AUTH_HEADER" "$API_URL")
        ACTION_REPO_URL=$(echo "$RESPONSE" | jq -r '.repository.clone_url')
        ACTION_BRANCH=$(echo "$RESPONSE" | jq -r '.head_branch')
        
        echo $ACTION_REPO_URL

        git clone --branch $ACTION_BRANCH $ACTION_REPO_URL
        cd $REPO_NAME

    - name: Echo Input 1
      shell: bash
      run: |
        echo ${{ inputs.input1 }}

    - name: Echo Input 2
      shell: bash
      run: |
        echo ${{ inputs.input2 }}

    - name: Cucumber Tests
      shell: bash
      run: |
        mvn clean test
